### ISSUE TITLE
Detect and list sites in a multi-site Drupal installation

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#1]
## Tasks

- [x] Add commands to show a list of sites present in the multi-site installation
  - [x] Detect sites using `sites/*/settings.php`
  - [x] Detect sites using drush alias definitions
  - [x] Preferably, the list of sites should be iterable in shell scripts
- [x] Use a `SiteDetector` service to make the code re-usable.

## Notes

- Only support D8+.
- Use PHP 8 or higher.

**Comment by jigarius** [comment]
Though this works now, I'd like to move some of the logic into a separate service, say, `SiteDetector` service to make the code reusable.
