### ISSUE TITLE
Run drush commands on all sites in a multi-site installation

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#2]
## Tasks

- [x] `drall st` – Shows status of all sites
- [x] `drall st --fields=site ...` works correctly
  - [x] Infinite arguments are sent to Drush correctly

**Comment by jigarius** [comment]
This works! I had to cheat a little bit because I couldn't find a way for Symfony Console to allow any number of `--options`. Here's how I [worked around this problem](https://stackoverflow.com/a/71281329/5238822).
