### ISSUE TITLE
Create a placeholder for keys in $sites

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#23]
## Requirements

- Currently, Drall uses site's subdir name as `--uri=@@uri`.
- However, certain commands work better if the `--uri` is a proper hostname
  - e.g. `drush uli` generates the correct URL with the correct `--uri`.
- Thus, it'll be good to have:
  - The `@@uri` placeholder that uses the keys in `$sites`.
  - A `@@dir` placeholder that uses the values in `$sites`.

## Tasks

- [x] Revisit and decide [placeholder nomenclature](https://github.com/jigarius/drall/issues/22)
- [x] `@@key` represents the keys in `$sites`.
  - Special `$sites` keys which include port numbers and paths. See [example.sites.php](https://api.drupal.org/api/drupal/sites%21example.sites.php/10.0.x).
  - Use existing libraries to convert these keys into a URI if possible?
- [x] `@@ukey` represents unique keys in `$sites`.
- [x] `@@dir` represents the site directory, i.e. replaces old `@@uri`.
- [x] Update documentation.

**Comment by jigarius** [comment]
This one is up next! The primary source of motivation is the `drall exec drush uli` command. Without a way to distinguish between `@@uri` and `@@dir`, the one-time login URLs are always annoyingly wrong.

**Comment by jigarius** [comment]
I just thought that maybe new commands should be added for `site:keys` and `site:ukeys`? Alternatively, a unified command named `site:list` could be created which would return a table containing:

```
Key | Ukey | Directory
example.com | example.ddev.site | example
example.ca | example.ddev.site | example
```

The user will then be able to filter by the respective column names. Alternatively, they can request only column like `drall site:list --field=directory`.
