### ISSUE TITLE
Run drush commands with --uri or with @alias

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#5]
## Requirements

All sites in a multi-site don't always have site aliases. Many projects rely on drush's `--uri` option to run the command on the correct site. Thus, we need to allow users to choose whether they want to use the URI or Drush aliases.

## Todo

- [x] If the user runs a command with `--uri=@@uri`, we replace the `@@uri` with individual site URIs before sending the command to Drush.
- [x] If the user runs a command with `@@site`, we replace the `@@site` with a site alias's name part, i.e. excluding the `env` part.
- [x] If the user runs a command without any of the above, we use `--uri=@@uri` by default.

**Comment by jigarius** [comment]
Though the feature works, a deeper thought and experimentation might be needed to determine whether it is safe to use the site's subdirectory name with `--uri` or if it is safer/better to use the site's hostname instead, i.e. keys of the `$site` array. Maybe a 3rd wildcard, `@@host` could be used?
