### ISSUE TITLE
Show progress bars during "drall exec"

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#53]
## Requirements

- Allow users to view the report in different formats.
- Some basic formats I to start with are shown below.

## Tasks

- [x] Use [Symfony Console's Progress Bar Helper](https://symfony.com/doc/current/components/console/helpers/progressbar.html)
- [x] Show progress bar by default.
- [x] Implement option to disable progress bar; `--drall-no-progress`.
- [x] Write tests?
- [x] Update documentation.

**Comment by jigarius** [comment]
Since the progress libraries can be useful in other projects, I decided to create a separate package for them: [jigarius/phprogress](jigarius/phprogress).

I will use that library in this project and improve it as necessary.
