### ISSUE TITLE
Handle SIGINT gracefully

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#81]
## Motivation

When running a command on multiple sites, the user might want to cancel the operation. Currently, when `Ctrl + C` is pressed, Drall stops immediately. It might make sense to finish at least the current operation before terminating.

## Tasks

- [x] When `SIGINT` is received,
  - [x] Display a message: `Stopping...`
  - [x] Do not execute any commands.
- [x] If `SIGINT` is received more than once, stop immediately.
