### ISSUE TITLE
Remove --drall prefixes from options

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#99]
### Motivation

- It is both difficult and ugly to have to type `--drall-*` all the time.
- Due to the `--drall-*` prefixes, it has not been possible to add shortcuts to the various Drall options.

### Tasks

- [x] Use syntax: `drall exec --opt1 --opt2 -- drush core:status --drush-opt1 --drush-opt2`
  - [x] On 4.x throw errors if `--drall-*` options are detected.
  - [x] On 4.x, force a `--` separator when options are used.
- [x] Remove prefixes from `--drall-*` options
  - [x] `--drall-debug` becomes `-d` or `--debug`
  - [x] `--drall-verbose` becomes `-v` or `--verbose`
  - [x] `--drall-group` becomes `-g` or `--group`
  - [x] `--drall-filter` becomes `-f` or `--filter`
  - [x] `--drall-workers` becomes `-w` or `--workers`
  - [x] `--drall-no-execute` becomes `-X` or `--dry-run` (didn't use `-n` because it conflicts with Symfony Console's `--no-interaction`).
  - [x] `--drall-no-progress` becomes `--no-progress`
- [x] Update tests
- [x] Update README
